/**
 * Icon barrel — exports Phosphor Icons using the SSR-safe path.
 * Use this file in BOTH server and client components.
 * For client-only interactive icon usage, you can also import directly from @phosphor-icons/react.
 */
export {
  House as IconHome,
  PlusCircle as IconPlusCircle,
  Plus as IconPlus,
  Package as IconBox,
  PaperPlaneTilt as IconSend,
  Crosshair as IconRadar,
  Users as IconUsers,
  Truck as IconTruck,
  Tag as IconTag,
  Clock as IconClock,
  MagnifyingGlass as IconSearch,
  X as IconX,
  SquaresFour as IconGrid,
  SignOut as IconLogout,
  Warning as IconAlert,
  TrendUp as IconTrend,
  Wallet as IconWallet,
  CurrencyInr as IconRupee,
  Check as IconCheck,
  CheckCircle as IconCheckCircle,
  ArrowRight as IconArrowRight,
  CaretRight as IconChevronRight,
  CaretDown as IconChevronDown,
  Printer as IconPrinter,
  MapPin as IconMapPin,
  Sparkle as IconSparkles,
  Calendar as IconCalendar,
  User as IconUser,
  Lock as IconLock,
  Phone as IconPhone,
  File as IconFile,
  Truck as IconLogo,
  List as IconMenu,
  Bell as IconBell,
  Gear as IconGear,
  ChartBar as IconChart,
  Timer as IconTimer,
  ArrowsClockwise as IconRefresh,
} from "@phosphor-icons/react/dist/ssr";
